version: "3.2"

networks:
  kong-network:
    ipam:
      config:
        - subnet: 10.5.0.0/16
    
services:
  custom-dns:
    image: coredns/coredns
    container_name: custom-dns
    command: -conf coredns-config/Corefile
    networks:
      kong-network:
        ipv4_address: 10.5.0.2
    volumes:
      - ./coredns:/coredns-config

  kong:
    build: .
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/test-config.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ANONYMOUS_REPORTS=off
      - KONG_LOG_LEVEL=debug
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      kong-network:
        ipv4_address: 10.5.0.3
    dns:
      - "10.5.0.2"
    networks:
      - kong-network
    depends_on:
      - custom-dns     
